services:
  postgres:
    image: postgres:16
    container_name: shop_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"   # <-- БЫЛО 5432:5432, СТАЛО 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop-net

  adminer:
    image: adminer
    container_name: shop_adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8081:8080"
    networks:
      - shop-net

networks:
  shop-net:

volumes:
  postgres_data: